// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKh0liMKYYCgU1MUVw7xlCWhepafaRQZc',
    appId: '1:373252388150:android:0d91d8a8fd1d55ab8eef97',
    messagingSenderId: '373252388150',
    projectId: 'mynotes-flutter-project-isaac2',
    storageBucket: 'mynotes-flutter-project-isaac2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjc6fGRX-RdW67rwN4CM5AzWyRSb8IE9k',
    appId: '1:373252388150:ios:cbb477fb90da418e8eef97',
    messagingSenderId: '373252388150',
    projectId: 'mynotes-flutter-project-isaac2',
    storageBucket: 'mynotes-flutter-project-isaac2.appspot.com',
    iosClientId: '373252388150-7shsrl3cemiqsilhp114kmnqjtq6vmra.apps.googleusercontent.com',
    iosBundleId: 'com.example.testing.mynotes',
  );
}
